services:
  accountCUD:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - 5432:5432

  springAccountCUD:
    image: mateusmedeirosgarcia/account-bantads:latest
    container_name: 'springAccountCUD'
    environment:
      - DATABASE_URL=accountCUD
      - DATABASE_PORT=5432
      - RABBITMQ_URL=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_QUEUE_CREATE=accountCUD.create
      - RABBITMQ_QUEUE_UPDATE=accountCUD.update
      - RABBITMQ_QUEUE_DELETE=accountCUD.delete
      - RABBITMQ_QUEUE_PATCH_CONSUMER=accountCUD.patch.consumer
      - RABBITMQ_QUEUE_DELETE_MANAGER=accountCUD.delete.manager
    ports:
      - 3000:8080
    depends_on:
      - orchestradorSaga

  accountR:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"

  springAccountR:
    image: mateusmedeirosgarcia/account-bantads:latest
    container_name: 'springAccountR'
    environment:
      - DATABASE_URL=accountR
      - DATABASE_PORT=5432
      - RABBITMQ_URL=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_QUEUE_CREATE=accountR.create
      - RABBITMQ_QUEUE_UPDATE=accountR.update
      - RABBITMQ_QUEUE_DELETE=accountR.delete
      - RABBITMQ_QUEUE_PATCH_CONSUMER=accountR.patch.consumer
      - RABBITMQ_QUEUE_DELETE_MANAGER=accountR.delete.manager
    ports:
      - 3001:8080
    depends_on:
      - orchestradorSaga

  springAccountRabbitMq:
    image: mateusmedeirosgarcia/rabbitmq-account-bantads
    container_name: 'springAccountRabbitMq'
    environment:
      - ACCOUNT_CUD_URL=springAccountCUD
      - ACCOUNT_CUD_PORT=8080
      - ACCOUNT_R_URL=springAccountR
      - ACCOUNT_R_PORT=8080
      - RABBITMQ_URL=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - 3002:8080
    depends_on:
      - orchestradorSaga

  address:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"

  addressSpring:
    image: mateusmedeirosgarcia/address-bantads:latest
    container_name: 'addressSpring-bantads'
    environment:
      - DATABASE_URL=address
      - DATABASE_PORT=5432
      - RABBITMQ_URL=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - 3004:8080

  customer:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - 5433:5432

  customerSpring:
    image: mateusmedeirosgarcia/customer-bantads:latest
    container_name: 'customer-bantads'
    environment:
      - DATABASE_URL=customer
      - DATABASE_PORT=5432
      - RABBITMQ_URL=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - 3003:8080
    depends_on:
      - orchestradorSaga

  manager:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - 5434:5432

  managerSpring:
    image: mateusmedeirosgarcia/manager-bantads:latest
    container_name: 'managerSpring-bantads'
    environment:
      - DATABASE_URL=manager
      - DATABASE_PORT=5432
      - RABBITMQ_URL=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - 3005:8080
    depends_on:
      - orchestradorSaga

  mongoAuthentication:
    image: 'mongo'
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'

  authenticationSpring:
    image: mateusmedeirosgarcia/authentication-bantads:latest
    container_name: 'authenticationSpring-bantads'
    environment:
      - MONGODB_HOST=mongoAuthentication
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=auth
      - MONGODB_USERNAME=username
      - MONGODB_PASSWORD=password
      - RABBITMQ_URL=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - 3006:8080
    depends_on:
      - orchestradorSaga

  orchestradorSaga:
    image: mateusmedeirosgarcia/orchestrator-saga-bantads:latest
    container_name: 'orchestradorSaga'
    environment:
      - RABBITMQ_URL=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - 3007:8080
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

  gateway:
    image: mateusmedeirosgarcia/gateway-bantads
    container_name: 'gateway-bantads'
    environment:
      - PORT=3000
      - ACCOUNT_URL=springAccountRabbitMq:8080
      - ADDRESS_URL=addressSpring:8080
      - CUSTOMER_URL=customerSpring:8080
      - MANAGER_URL=managerSpring:8080
      - AUTHENTICATION_URL=authenticationSpring:8080
      - ORCHESTRATOR_URL=orchestradorSaga:8080
    ports:
      - 3333:3000

  front:
    image: mateusmedeirosgarcia/bantads
    container_name: 'bantads'
    ports:
      - 80:80
