services:
  accountCUD:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"

  springAccountCUD:
    image: mateusmedeirosgarcia/account-bantads:latest
    container_name: 'springAccountCUD'
    environment:
      - DATABASE_URL=accountCUD
      - DATABASE_PORT=5432
    ports:
      - 3000:8080

  accountR:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"

  springAccountR:
    image: mateusmedeirosgarcia/account-bantads:latest
    container_name: 'springAccountR'
    environment:
      - DATABASE_URL=accountR
      - DATABASE_PORT=5432
    ports:
      - 3001:8080

  springAccountRabbitMq:
    image: mateusmedeirosgarcia/rabbitmq-account-bantads
    container_name: 'springAccountRabbitMq'
    environment:
      - ACCOUNT_CUD_URL=springAccountCUD
      - ACCOUNT_CUD_PORT=8080
      - ACCOUNT_R_URL=springAccountR
      - ACCOUNT_R_PORT=8080
      - RABBITMQ_URL=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - 3002:8080

  customer:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - 5434:5432
  manager:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - 5435:5432
  authentication:
    image: mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2019!
    ports: 
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672

